const translations = {
  zh: { newRepair:'新增報修',viewRecords:'瀏覽紀錄',title:'設備報修',subtitle:'掃描設備 QR Code，拍下異常狀況後存檔。',scanDevice:'掃描設備',notScanned:'尚未掃描',openScanner:'開啟相機掃描 QR Code',cameraHint:'請允許瀏覽器使用相機。',assetCode:'設備編號／QR Code 內容',assetPlaceholder:'掃描後自動帶入，也可手動輸入',takePhotos:'拍攝異常',choosePhotos:'拍照或選擇照片',photoHint:'必填，最多 3 張',reason1:'異常原因',reason2:'異常原因 2',selectReason:'請選擇原因',selectReasonOptional:'請選擇原因（選填）',pleaseSelect:'請選擇',noise:'有異音',leak:'漏水',inactive:'不作動',description:'問題描述',details:'異常情形（選填）',descriptionPlaceholder:'請補充設備的異常情形…',email:'您的電子郵件',emailLabel:'電子郵件',save:'存檔',saved:'紀錄已存檔',createAnother:'建立另一筆',cameraUnsupported:'此瀏覽器無法開啟相機，請手動輸入設備編號。',aimQr:'將 QR Code 對準框線。',cameraDenied:'相機權限被拒絕，請在瀏覽器設定中允許相機。',cameraFailed:'無法開啟相機：',scanComplete:'掃描完成',readValue:'已讀取：',photo:'異常照片',photosUnit:'張',hasAssetCode:'已有設備編號',photoRequired:'請至少拍攝或選擇一張異常照片。',ticket:'單號：',serverSaved:'JSON 已儲存至 records 目錄。',browserSaved:'紀錄已儲存在此瀏覽器。',recordsTitle:'報修紀錄',recordsSubtitle:'顯示儲存在此裝置瀏覽器中的紀錄。',noRecords:'目前沒有報修紀錄。',deleteRecord:'刪除',photoCount:'照片',createdAt:'建立時間',confirmDelete:'確定刪除這筆紀錄嗎？' },
  en: { newRepair:'New repair',viewRecords:'View records',title:'Equipment Repair',subtitle:'Scan the equipment QR code, take photos, and save the report.',scanDevice:'Scan equipment',notScanned:'Not scanned',openScanner:'Open camera to scan QR code',cameraHint:'Please allow camera access.',assetCode:'Asset ID / QR code value',assetPlaceholder:'Filled after scanning, or enter manually',takePhotos:'Take photos',choosePhotos:'Take or choose photos',photoHint:'Required, up to 3 photos',reason1:'Issue reason',reason2:'Issue reason 2',selectReason:'Select a reason',selectReasonOptional:'Select a reason (optional)',pleaseSelect:'Please select',noise:'Abnormal noise',leak:'Water leakage',inactive:'Not operating',description:'Problem description',details:'Details (optional)',descriptionPlaceholder:'Add more details about the issue…',email:'Your email',emailLabel:'Email address',save:'Save',saved:'Record saved',createAnother:'Create another',cameraUnsupported:'This browser cannot access the camera. Enter the asset ID manually.',aimQr:'Align the QR code inside the frame.',cameraDenied:'Camera access was denied. Allow it in browser settings.',cameraFailed:'Unable to open camera:',scanComplete:'Scan complete',readValue:'Read:',photo:'Issue photo',photosUnit:'photos',hasAssetCode:'Asset ID entered',photoRequired:'Please take or choose at least one photo.',ticket:'Ticket:',serverSaved:'JSON was saved in the records directory.',browserSaved:'The record was saved in this browser.',recordsTitle:'Repair Records',recordsSubtitle:'Records saved in this browser are shown below.',noRecords:'No repair records yet.',deleteRecord:'Delete',photoCount:'Photos',createdAt:'Created',confirmDelete:'Delete this record?' }
};
const currentLanguage = (navigator.language || '').toLowerCase().startsWith('zh') ? 'zh' : 'en';
const t = key => translations[currentLanguage][key] || key;
document.documentElement.lang = currentLanguage === 'zh' ? 'zh-Hant' : 'en';
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = t(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); });
  document.title = currentLanguage === 'zh' ? '行動報修 Demo' : 'Mobile Repair Demo';
});
